name: JUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: JDK をセットアップ (Java 21)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # AdoptOpenJDK (Eclipse Temurin)
          java-version: '21'
          cache: 'maven'  # Gradle の場合は 'gradle'

      - name: run test
        run: mvn test
